server:
  #端口
  port: 8080
  servlet:
    #设置项目访问名称
    context-path: /springBootDemo
spring:
  datasource:
    druid:
      driver-class-name: ${driverClass}
      url: ${url}
      username: ${user}
      password: ${password}
      # 初始化大小，最小，最大
      initial-size: 3
      min-idle: 3
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 200000
      validation-query: select
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    host: www.b0c0.com
    port: 6379
    #没有密码则留空
    password: password
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 0
        max-wait: 100
  thymeleaf:
    #禁用thymeleaf的缓存
    cache: false
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录,添加那个目录的文件需要restart
      additional-paths: src/main/java
      exclude: templates/**
mybatis:
  #设置别名，在mapper.xml中可直接写类名即可，不必再写com.lds.springbootdemo.domain
  type-aliases-package: com.lds.springbootdemo.domain
  #mybatis的mapper映射路径
  mapper-locations: classpath:mybatis/mapper/*.xml